no more confirm, high, and low

diff --git a/bin/gpio b/bin/gpio
--- a/bin/gpio
+++ b/bin/gpio
@@ -59,7 +59,6 @@ Usage
 $(basename "$0") export [OPTIONS] HEADER PIN_NO
 
 Options:
-  -c, --confirm   Apply the changes requested.
   --high          Initializes the pin high, implies --out
   -i, --in        Set the pin direction to in
   --low           Initializes the pin to low, implies --out
@@ -77,7 +76,6 @@ Usage
 $(basename "$0") unexport [OPTIONS] HEADER PIN_NO
 
 Options:
-  -c, --confirm   Apply the changes requested.
 
 HELP
 }
@@ -114,9 +112,6 @@ function gpio_export() {
     case "$arg" in
       --debug|--no-debug)
         ;;
-      --confirm)
-        local -r confirm=yes
-        ;;
       --high)
         local direction="$(one_direction "$direction" high)"
         debug "direction is now '${direction}'"
@@ -139,19 +134,7 @@ function gpio_export() {
     esac
   done
 
-  if [ "${#pin_info[@]}" -eq 0 ]; then
-    printf "Both HEADER and PIN_NO are required arguments.\n\n" >&2
-    help_text
-    exit 1
-  elif [ "${#pin_info[@]}" -eq 1 ]; then
-    printf "PIN_NO is required argument.\n\n" >&2
-    help_text
-    exit 1
-  elif [ "${#pin_info[@]}" -gt 2 ]; then
-    printf "Too many arguments passed, expected 2 but got %d.\n\n" "${#pin_info[@]}"
-    help_text
-    exit 1
-  fi
+  validate_pin_info "${pin_info[@]}"
 
   local -r header="${pin_info[0]}"
   local -r pin="${pin_info[1]}"
@@ -160,19 +143,14 @@ function gpio_export() {
 
   if [ ! -e "$gpio_pin_path" ]; then
     debug "Exporting ${header} ${pin} as GPIO pin ${gpio_pin}."
-    if [ -n "$confirm" ]; then
-      printf "%d" "$gpio_pin" > "$export_path"
-    fi
+    printf "%d" "$gpio_pin" > "$export_path"
   else
     debug "${header} ${pin} is already exported as GPIO pin ${gpio_pin}."
   fi
 
   if [ -n "$direction" ]; then
     debug "Initializing direction to '${direction}'"
-
-    if [ -n "$confirm" ]; then
-      printf "$direction" > "$gpio_pin_path"/direction
-    fi
+    printf "$direction" > "$gpio_pin_path"/direction
   fi
 }
 
@@ -187,28 +165,13 @@ function gpio_unexport() {
     case "$arg" in
       --debug|--no-debug)
         ;;
-      --confirm)
-        local -r confirm=yes
-        ;;
       *)
         pin_info+=("$arg")
         ;;
     esac
   done
 
-  if [ "${#pin_info[@]}" -eq 0 ]; then
-    printf "Both HEADER and PIN_NO are required arguments.\n\n" >&2
-    help_text
-    exit 1
-  elif [ "${#pin_info[@]}" -eq 1 ]; then
-    printf "PIN_NO is required argument.\n\n" >&2
-    help_text
-    exit 1
-  elif [ "${#pin_info[@]}" -gt 2 ]; then
-    printf "Too many arguments passed, expected 2 but got %d.\n\n" "${#pin_info[@]}"
-    help_text
-    exit 1
-  fi
+  validate_pin_info "${pin_info[@]}"
 
   local -r header="${pin_info[0]}"
   local -r pin="${pin_info[1]}"
@@ -217,11 +180,87 @@ function gpio_unexport() {
 
   if [ -e "$gpio_pin_path" ]; then
     debug "Unexporting ${header} ${pin} as GPIO pin ${gpio_pin}."
-    if [ -n "$confirm" ]; then
-      printf "%d" "$gpio_pin" > "$export_path"
-    fi
+    printf "%d" "$gpio_pin" > "$unexport_path"
   else
     debug "${header} ${pin} is not exported as GPIO pin ${gpio_pin}."
+  fi
+}
+
+function gpio_high() {
+  local arg
+  local -a pin_info=()
+
+  while [ $# -gt 0 ]; do
+    arg="$1"
+    shift
+
+    case "$arg" in
+      --debug|--no-debug)
+        ;;
+      *)
+        pin_info+=("$arg")
+        ;;
+    esac
+  done
+
+  local -r header="${pin_info[0]}"
+  local -r pin="${pin_info[1]}"
+  local -r -i gpio_pin="$(gpio_pin "$header" "$pin")"
+  local -r gpio_pin_path="$(gpio_pin_path "$gpio_pin")"
+
+  if [ -e "$gpio_pin_path" ]; then
+    debug "Setting ${header} ${pin} as GPIO pin ${gpio_pin} HIGH."
+    printf "1" > "$gpio_pin_path"/value
+  else
+    debug "${header} ${pin}, GPIO pin ${gpio_pin}, is not exported."
+    return 1
+  fi
+}
+
+function gpio_low() {
+  local arg
+  local -a pin_info=()
+
+  while [ $# -gt 0 ]; do
+    arg="$1"
+    shift
+
+    case "$arg" in
+      --debug|--no-debug)
+        ;;
+      *)
+        pin_info+=("$arg")
+        ;;
+    esac
+  done
+
+  local -r header="${pin_info[0]}"
+  local -r pin="${pin_info[1]}"
+  local -r -i gpio_pin="$(gpio_pin "$header" "$pin")"
+  local -r gpio_pin_path="$(gpio_pin_path "$gpio_pin")"
+
+  if [ -e "$gpio_pin_path" ]; then
+    debug "Setting ${header} ${pin} as GPIO pin ${gpio_pin} LOW."
+    printf "0" > "$gpio_pin_path"/value
+  else
+    debug "${header} ${pin}, GPIO pin ${gpio_pin}, is not exported."
+    return 1
+  fi
+}
+
+function validate_pin_info() {
+  if [ $# -eq 0 ]; then
+    printf "Both HEADER and PIN_NO are required arguments.\n\n" >&2
+    help_text
+    return 1
+  elif [ $# -eq 1 ]; then
+    printf "PIN_NO is required argument.\n\n" >&2
+    help_text
+    return 1
+  elif [ $# -gt 2 ]; then
+    printf "Too many arguments passed, expected 2 but got %d.\n\n" "$#"
+    help_text
+    return 1
   fi
 }
 
