whoops

diff --git a/bin/gpio-export b/bin/gpio-export
--- a/bin/gpio-export
+++ b/bin/gpio-export
@@ -24,10 +24,10 @@ function one_direction() {
   local -r desired="${2}"
 
   if [ "$current" == "in" ] && [ "$desired" != "in" ]; then
-    printf "You cannot set the direction to '%s' after already setting it to '%s'\n" "$desired" "$current" >&2
+    printf "You cannot set the direction to '%s' after already setting it to '%s'.\n" "$desired" "$current" >&2
     return 1
   else
-    if [ "$current" == "out" ]; then
+    if [ -z "$current" ] || [ "$current" == "out" ]; then
       printf "%s\n" "$desired"
     else
       printf "%s\n" "$current"
@@ -58,7 +58,7 @@ function main() {
         local direction="$(one_direction "$direction" high)"
         debug "direction is now '${direction}'"
         ;;
-      -i|--input)
+      -i|--in)
         local direction="$(one_direction "$direction" in)"
         debug "direction is now '${direction}'"
         ;;
@@ -69,7 +69,7 @@ function main() {
       --no-debug)
         local -x debug=""
         ;;
-      -o|--output)
+      -o|--out)
         local direction="$(one_direction "$direction" out)"
         debug "direction is now '${direction}'"
         ;;
@@ -91,7 +91,7 @@ function main() {
     printf "Too many arguments passed, expected 2 but got %d.\n\n" "${#pin_info[@]}"
     help_text
     exit 1
-  fi 
+  fi
 
   local -r header="${pin_info[0]}"
   local -r pin="${pin_info[1]}"
@@ -106,7 +106,7 @@ function main() {
   else
     debug "${header} ${pin} is already exported as GPIO pin ${gpio_pin}."
   fi
-  
+
   if [ -n "$direction" ]; then
     debug "Initializing direction to '${direction}'"
 
